configured_endpoints: 40
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/chunkify%2Fchunkify-a26d4faf60b2db2b22b8ebfad106d8a9a4379a04efbf16de0d1b61ca73d03b94.yml
openapi_spec_hash: 44595338c7bca0dfca5a46abefafb032
config_hash: ba46c34a1b57aba3c35375ea3ac6c749
